baseURL = "http://example.org/"
languageCode = "en-us"
title = "Bananas"
theme = "alpha-church"

enableEmoji = true
customCSS = ["", ""]

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""


[taxonomies]
  tag = "tags"
  preacher = "preachers"
  series = "series"

#This theme can generate a multi-level theme.
#Use the weight= to specify the order of menu items, and the parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About Us"
    url = "about"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 4

# Paramaters for the whole site
[params]
  title = "Dorifto"
  subtitle = "a basic page about dorifting"
  author = "Dr Dorito"

  [params.podcast]
    title = "Listen doriftos"
    subtitle = ""
    summary = "Alpha-Church sermons, talks, messages—podcasted."
    email = "test@example.com"
    image = "img/podcast-cover.jpg"
    category = "Religion & Spirituality"
    sub_category = "Christianity"

  [params.map]
    # For Open Street Map widgets
    latitude = "37.639374"
    longitude = "140.367836"
    zoom = "16"

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify" or "formspree"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (or elase users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree email address.
    service = "netlify"
    confirm_page = "/contact_thanks"
    # formspree_email=""

  #Paramaters for the home/landing page
  [params.landing]

    [params.landing.banner]
      image = "churchy/images/banner.jpg"

      [[params.landing.banner.button]]
        url = "/contact"
        text = "Get in touch"
        type = "special"

        [[params.landing.banner.button]]
        url = "/about"
        text = "Find out more"

    #Details for the box below the banner
    [params.landing.services]
      title = "For all dorifto purposes"
      text = "Dorifto commences here:"
      map_location = "Ebisu Circuit"

    [params.landing.feature_icons]
      #These feature icons look best if there's an even number of them.
      enable = true

      #Accent is a colour defined in the CSS file. Choose between 1 and 5
      [[params.landing.feature_icons.tile]]
        icon = "fa-car"
        icon_pack = "fa"
        accent = "1"
        title = "Dorift"
        text = "Growing people who dorifto our community."

      [[params.landing.feature_icons.tile]]
        icon = "fa-users"
        icon_pack = "fas"
        accent = "2"
        title = "Friends"
        text = "Meeting together to bond over dorifto."

      [[params.landing.feature_icons.tile]]
        icon = "fa-trash"
        icon_pack = "fa"
        accent = "5"
        title = "Crash"
        text = "Crashing encouragement to one-another."

      [[params.landing.feature_icons.tile]]
        icon = "fa-heartbeat"
        icon_pack = "fas"
        accent = "3"
        title = "Love"
        text = "Knowing Love. Being Loved."

    [params.landing.feature_images]
      #These feature images look best if there's an even number of them.
      enable = true

      [[params.landing.feature_images.tile]]
        image = "img/freely-10057.jpg"
        title = "Dorifo Dorito"
        text = "How Doritos and Doriftos are connected."
        url = "/dorifto-dorito"
        button_text = "Learn more"

      [[params.landing.feature_images.tile]]
        image = "img/freely-26905.jpg"
        title = "Midweek Doritos"
        text = "Want more during the week?"
        url = "https://www.amazon.com/Doritos/pages/3024658011"
        button_text="Eat Dorito today!"

    [params.landing.CTA]
      heading = "Get in touch!"
      message = "We'd love to hear from you."

    [params.footer]
      copyright = "[CC0 (public domain)](http://creativecommons.org/publicdomain/zero/1.0/)"

    [[params.links]]
      service = "Twitter"
      icon = "fa-twitter"
      icon_pack = "fab"
      link = "//twitter.com/"

    [[params.links]]
      service = "Facebook"
      icon = "fa-facebook"
      icon_pack = "fab"
      link = "//facebook.com/"

    [[params.links]]
      service = "Podcast"
      icon = "fa-podcast"
      icon_pack = "fas"
      link = "/sermons/index.xml"

    [[params.links]]
      service = "Full RSS Feed"
      icon = "fa-rss"
      icon_pack = "fas"
      link = "/index.xml"
